package tech.sanak.deck.model;

//import jakarta.persistence.Entity;
//import jakarta.persistence.GeneratedValue;
//import jakarta.persistence.GenerationType;
//import jakarta.persistence.Id;
import jakarta.persistence.*;
//import lombok.AllArgsConstructor;
//import lombok.Builder;
//import lombok.Data;
//import lombok.NoArgsConstructor;
import lombok.*;

/**
 * Represents a flashcard entity stored in the database.
 * This entity is automatically mapped to a table using JPA.
 *
 * Used by Spring JPA repositories for CRUD operations.
 */

@Entity // JPA: Marks this class as a persistent entity mapped to a table in the database

@Data   // Lombok: getter, setter, tostring(), equals(), hashCode()
//@Getter
//@Setter
@NoArgsConstructor // Lombok: No arguments constructor for ORM
@AllArgsConstructor // Lombok: All arguments constructor
@Builder    // Lombok: enables the builder pattern
public class Flashcard {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;    // Primary key, auto-generated by the database

    public boolean publicCard() {
        return publicCard;
    }

    //  Flashcard is public if publicCard == true or/and owner == null
    @Column(name = "is_public", nullable = false)
    private boolean publicCard = false;

    public void setPublic(boolean aPublic) {
        publicCard = aPublic;
    }

    @ManyToOne
    @JoinColumn(name = "user_id")  // foreign key to User
    private User owner;  // Owner of the flashcard - null means globa/public
                         // (if publicCard == true)

    private String front;   // The front side of the flashcard (question)
    private String back;    // The back side of the flashcard (answer)
    private String category;    // Category or topic of the flashcard



}
