package tech.sanak.deck.model;

//import jakarta.persistence.Entity;
//import jakarta.persistence.GeneratedValue;
//import jakarta.persistence.GenerationType;
//import jakarta.persistence.Id;
import jakarta.persistence.*;
//import lombok.AllArgsConstructor;
//import lombok.Builder;
//import lombok.Data;
//import lombok.NoArgsConstructor;
import lombok.*;

/**
 * Represents a flashcard entity stored in the database.
 * This entity is automatically mapped to a table using JPA.
 */

@Entity // JPA: Marks this class as a persistent entity mapped to a table in the database
        // JPA: Klasa to encja mapowana do tabeli w bazie

@Data   // Lombok: Generuje gettery, settery, tostring(), equals(), hashCode()
//@Getter
//@Setter
@NoArgsConstructor // Lombok: generuje konstruktor bezargumentowy
@AllArgsConstructor // Lombok: generuje konstruktor ze wszystkimi argumentami
@Builder    // Lombok: enables the builder pattern
public class Flashcard {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;    // Primary key, auto-generated by the database

    @Column(nullable = false)
    //  Flashcard is public if isPublic == true or/and owner == null
    private boolean isPublic = false;

    @ManyToOne
    @JoinColumn(name = "user_id")
    private User owner;

    private String front;   // The front side of the flashcard (question)
    private String back;    // The back side of the flashcard (answer)
    private String category;    // Category or topic of the flashcard
}
